config/routes.rb
Rails.application.routes.draw do
  root 'post#index'
  resources :post
  
  devise_for :admins

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def new
  	@post =Post.new
  end

  def index

  end

  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               <!-- <a class="navbar-brand" href="#">Start Bootstrap</a>-->s
                <%= link_to "Kursy u MIchala",root_url, class: "navbar-brand" %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                    	<%= link_to "Nauczanie", post_index_path %>
                    </li>
                    <li>
                    	<%= link_to "Zaloguj sie ",new_admin_session_path %> 
                    </li>
                 
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
<br><br><br>
<div class="cointeiner">
   <div class="row">
   		<div class="col-lg-12 text-center">
   		<% flash.each do |a, b|%>
   		<div class=" alert alert-success"><%=b %></div>

		<%end%>
			<%= yield %>
   		
		</div>
	</div>
</div>
</body>
</html>

app/views/post/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>
<%= simple_form_for @post do |form| %>
  <%= form.input :author, as: :text %>
  <%= form.submit%>
<% end %>

app/views/post/new.html.erb
<h1>Post#new</h1>
<p>Find me in app/views/post/new.html.erb</p>

app/views/post/show.html.erb
<h1>Post#show</h1>
<p>Find me in app/views/post/show.html.erb</p>